services:

  core-backend:
    build:
      context: .
      dockerfile: src/core_backend/Dockerfile
    container_name: core-backend
    ports:
      - '8000:8000'
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - APP_ENV=prod
    depends_on:
      - postgres
      - prometheus
    volumes:
      - ./docker/prometheus/targets.json:/app/docker/prometheus/targets.json
      - prom_shared_data:/etc/prometheus
    networks:
      - monitor-net

  core-frontend:
    build:
      context: .
      dockerfile: src/core_frontend/Dockerfile
    container_name: core-frontend
    ports:
      - '80:80'
    restart: unless-stopped
    depends_on:
      - core-backend
    networks:
      - monitor-net

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - '9090:9090'
    restart: always
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./docker/prometheus/targets.json:/etc/prometheus/targets.json:ro
      - prometheus_data:/prometheus
      - prom_shared_data:/etc/prometheus    # share with core-backend container
    networks:
      - monitor-net

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: unless-stopped
    networks:
      - monitor-net
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
      POSTGRES_DB: main_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  monitor-net:
    driver: bridge

volumes:
  prometheus_data:
  postgres_data:
  prom_shared_data:

# docker compose -f docker_compose.yml up -d --build

