global:
  scrape_interval: 5s
  scrape_timeout: 2s
  evaluation_interval: 10s
#alerting:
#  alertmanagers:
#  - static_configs:
#    - targets: []
#    scheme: http
#    timeout: 10s
#    api_version: v1
scrape_configs:
  - job_name: 'dynamic-metrics-craw'
    honor_timestamps: true
    scrape_interval: 5s
    scrape_timeout: 2s
    file_sd_configs:
      - files:
          - /etc/prometheus/targets.json
